---
- name: Install php5
  apt: pkg=php5-xdebug state=latest

- name: Determine location of xdebug.so
  action: command locate xdebug.so
  register: get_xdebug_path

- name: Configure PHP xdebug for Apache
  lineinfile: dest=/etc/php5/apache2/conf.d/20-xdebug.ini line="{{ item }}"
  notify: restart apache
  with_items:
    - xdebug.remote_enable=1
    - xdebug.remote_autostart=1
    - xdebug.remote_connect_back=1
    - xdebug.max_nesting_level=1000
    - xdebug.remote_log=/tmp/xdebug.log
    - xdebug.idekey=Phpstorm
