---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    droplets:
      - { name: ansible-pull-request-deploy, group: "www" }
  tasks:
  - name: Create new DigitalOcean droplet
    digital_ocean: >
      state=present
      command=droplet
      name={{ item.name }}
      unique_name=yes
      private_networking=yes
      size_id=512mb
      region_id=ams2
      image_id=ubuntu-14-04-x64
      ssh_key_ids=1676458
      wait_timeout=500
    register: created_droplets
    with_items: droplets

  - name: Debug Created Droplets
    debug: var=created_droplets
    when: created_droplets.results is defined

  - name: Add new host to our vars
    add_host:
      name: "{{ item.0.droplet.networks.v4.1.ip_address }}"
      groups: "do,{{ droplets[item.0].group }},{{ item.0.droplet.name }}"
    when: item.0.droplet is defined
    with_indexed_items: created_droplets.results

  - name: Debug hosts
    debug: msg="System {{ inventory_hostname }}"

- hosts: www
  remote_user: root
  sudo: false
  gather_facts: true
  vars:
    project_root: /var/www/ansible-pull-request-deploy
    servername: ansible-pull-request-deploy
  vars_files:
    - vars/cloud.yml
  roles:
    - app
    - nginx
    - php
    - server
